### ISSUE TITLE
[grid] Unexpected takeover artefacts in Safari & Firefox

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/neon-animated-pages#1]
Video (play at 0.25x speed): https://www.youtube.com/watch?v=FvQnNyj95HY&feature=youtu.be
Tested against: neon-animated-pages/demo/grid/

When selecting a grid item in Safari or Firefox, a full-screen takeover occurs..

![screen shot 2015-05-12 at 10 30 55](https://cloud.githubusercontent.com/assets/110953/7583999/21520eb2-f892-11e4-9b22-94b5e7b30862.png)

before returning to this state

![screen shot 2015-05-12 at 10 31 08](https://cloud.githubusercontent.com/assets/110953/7584006/31c18750-f892-11e4-98b4-2401eb8a619a.png)

after which, the correct takeover animation occurs. 

![screen shot 2015-05-12 at 10 32 46](https://cloud.githubusercontent.com/assets/110953/7584028/66f7d686-f892-11e4-9fb7-bf90791f4a74.png)

I haven't noticed this in Chrome (or at least, if it occurs it's quick enough that I don't see it). This may be related to the Web Animations polyfill.

**Comment by morethanreal** [comment]
Fixed in 240733416d882b87aeec1871a97aa438302e17e1.
