### ISSUE TITLE
animated-dropdown origins inconsistent in Chrome vs. other browsers

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/neon-animated-pages#2]
Video: https://www.youtube.com/watch?v=CKLkdJzOic8

In Chrome we correctly animate from the top-left corner using a `transformOrigin` of 0,0. 

![screen shot 2015-05-12 at 10 51 37](https://cloud.githubusercontent.com/assets/110953/7584369/e95597e2-f894-11e4-9a10-ac100bef83bd.png)

This appears to be different in other browsers where the origin seems to be a distance away from this corner. Verified in Safari.

![screen shot 2015-05-12 at 10 51 53](https://cloud.githubusercontent.com/assets/110953/7584371/ee89d020-f894-11e4-9f0b-3d934c093bec.png)

**Comment by morethanreal** [comment]
Fixed in 240733416d882b87aeec1871a97aa438302e17e1.
